package com.dziobsoft.doctormanager.doctor.models;

public enum VisitType {
    KONSULTACJA_PSYCHIATRYCZNA,
    BADANIE_OGOLNE,
    INTERWENCJA_KRYZYSOWA,
    KONSULTACJA_FIZJOTERAPEUTYCZNA,
    WYBIELANIE_ZEBOW,
    BADANIE_STOMATOLOGICZNE,
    KONSULTACJA_GINEKOLOGICZNA,
    KONSULTACJA_CHIRURGICZNA,
    KONSULTACJA_DERMATOLOGICZNA
}
